__title__ = "kanjize"
__description__ = "Easy converter between Kanji-Number and Integer"
__url__ = "https://github.com/nagataaaas/kanjize"
__version_info__ = ("1", "5", "0")
__version__ = ".".join(__version_info__)
__author__ = "Yamato Nagata"
__author_email__ = "nagata@nagata.pro"
__maintainer__ = "Yamato Nagata"
__license__ = "MIT"
__copyright__ = "(c) 2019-2023 by Yamato Nagata"
