__title__ = "kanjize"
__description__ = "Easy converter between Kanji-Number and Integer"
__url__ = "https://github.com/delta114514/kanjize"
__version_info__ = ("0", "1", "0")
__version__ = ".".join(__version_info__)
__author__ = "Yamato Nagata"
__author_email__ = "chickenwingswillfly@gmail.com"
__maintainer__ = "Yamato Nagata"
__license__ = "MIT"
__copyright__ = "(c) 2019 by Yamato Nagata"
